// viewpoints - interactive linked scatterplots and more.
// copyright 2005 Creon Levit, all rights reserved.
//***************************************************************************
// File name: symbol_menu.h
//
// Class definitions: none
//
// Classes referenced:
//   Various FLTK classes
//
// Required packages: none
//
// Compiler directives:
//   Requires WIN32 to be defined
//
// Purpose: External method generated by Fast Light User Interface Designer 
//  (fluid) version 1.0108 to generate and manage the symbol menu
//
// General design philosophy: n/a
//
// Author: Creon Levit    2007
// Modified: P. R. Gazis  12-JUL-2007
//***************************************************************************

// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef symbol_menu_h
#define symbol_menu_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Choice.H>
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_symbol[];
#endif
