// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef symbol_menu_h
#define symbol_menu_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Choice.H>
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_symbol[];
#endif
